// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDso2bliVi1LX5KE5VRGMLg_S5qO2otjV0',
    appId: '1:1021945501127:web:4741f4f8111e97f8f8b5e2',
    messagingSenderId: '1021945501127',
    projectId: 'foora-app',
    authDomain: 'foora-app.firebaseapp.com',
    storageBucket: 'foora-app.firebasestorage.app',
    measurementId: 'G-LK3F2TNJNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6fv1layStE-kEe_m5jof5SUuRfKxsxQU',
    appId: '1:1021945501127:android:2cbea3f90b719047f8b5e2',
    messagingSenderId: '1021945501127',
    projectId: 'foora-app',
    storageBucket: 'foora-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhvFO7RNQ_YxNXQQ9iRj_WF6ew8TSrTCU',
    appId: '1:1021945501127:ios:d43cff5a7282df38f8b5e2',
    messagingSenderId: '1021945501127',
    projectId: 'foora-app',
    storageBucket: 'foora-app.firebasestorage.app',
    iosClientId: '1021945501127-f6guj20obph09lup75shimqdpku1620f.apps.googleusercontent.com',
    iosBundleId: 'com.foora.foora',
  );
}
